accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

market/urls.py
from django.contrib import admin
from django.urls import path, include
from products import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name="index"),
    path('accounts/', include("accounts.urls")),
    path('products/', include("products.urls")),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path("new/", views.new, name="new"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update", views.update, name="update"),
    path("<int:pk>/delete", views.delete, name="delete"),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Users(AbstractUser):
    pass

products/models.py
from django.db import models

# Create your models here.
class Products(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    price = models.IntegerField()

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UsersForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username','email', 'password1', 'password2')

        

products/forms.py
from django import forms
from .models import Products

class PostForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = "__all__"
        labels = {
            'title' : '상품명',
            'content' : '상품 설명',
            'price' : '가격',
        }

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect , render
from .forms import UsersForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

def signup(request):
    if request.method == "POST":
        form = UsersForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("index")
    else:
        form = UsersForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)
    

# @require_http_methods(["GET", "POST"])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_url = request.GET.get('next') or 'index'
            return redirect(next_url)
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)

# @require_POST
def logout(request):
    if request.method == "POST":
        auth_logout(request)
    return redirect('index')

products/views.py
from django.shortcuts import render
from .forms import PostForm
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_http_methods, require_POST, require_GET
from .models import Products

@require_POST
def delete(request, pk):
    if request.method == "POST":
        product = Products.objects.get(pk=pk)
        product.delete()
        return redirect("index")
    return redirect("products:detail", pk)



def index(request):
    products = Products.objects.all()
    context = {
        'products': products,
    }
    return render(request, "products/index.html" ,context)


def detail(request, pk):
    product = Products.objects.get(pk=pk)
    context = {
        'product': product,
    }
    return render(request, "products/detail.html" ,context)

@require_http_methods(["GET", "POST"])
def update(request, pk):
    product = Products.objects.get(pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save()
            return redirect('products:detail', product.pk)
    else:
        form = PostForm(instance=product)
        context = {
            'form': form,
            'product': product,
        }
    return render(request, 'products/update.html', context)

# @login_required
def new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            # post = form.save(commit=False)
            # post.user = request.user
            form.save()
            return redirect("index")
    else:
        form = PostForm()
    context = {"form": form}
    return render(request, "products/newposts.html", context)

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
    <h1>로그인</h1>

    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">로그인</button>
    </form>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
    <h1>회원가입</h1>
    <form action="{% url "accounts:signup" %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">회원가입</button>
    </form>

{% endblock %} 

products/templates/products/detail.html
{% extends "base.html" %}

{% block content %}

<p> {{ product.title }}</p>
<p> {{ product.content }}</p>
<p> {{ product.price }}</p>

<a href="{% url "products:update" product.pk %}">수정</a>


<form action="{% url "products:delete" product.pk %}" method="POST"> 
    {% csrf_token %}
    <input type="submit" value="zzz">
</form>




{% endblock %} 

products/templates/products/index.html
{% extends "base.html" %}

{% block content %}

<a href="{% url "products:new" %}"> 작성해버렷 </a>





<ol>
    {% for product  in products %} 
    <li><a href="{% url "products:detail" product.pk %}">{{ product.title }}</a></li>
    {% endfor %}
</ol>


{% endblock %} 

products/templates/products/newposts.html
{% extends "base.html" %}

{% block content %}
    <h1>게시물!!</h1>
    <form action="{% url "products:new" %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">게시물 작성</button>
    </form>

{% endblock %} 

products/templates/products/products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

products/templates/products/update.html
{% extends "base.html" %}

{% block content %}
    <h1>수정잉</h1>
    <form action="{% url "products:update" product.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">게시물 수정잉</button>
    </form>

{% endblock %} 

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <form action="{% url "accounts:logout" %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="탈출해">
    </form>



    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

</body>
</html>